# Generated by Django 3.2.8 on 2021-12-03 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'OpiodPages_credential',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drugid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('drugname', models.CharField(max_length=30)),
                ('isopioid', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'OpiodPages_drug',
            },
        ),
        migrations.CreateModel(
            name='pd_prescriber',
            fields=[
                ('npi', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=11)),
                ('lname', models.CharField(max_length=11)),
                ('gender', models.CharField(max_length=1)),
                ('specialty', models.CharField(max_length=62)),
                ('isopioidprescriber', models.BooleanField(default=False)),
                ('totalprescriptions', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'OpiodPages_pd_prescriber',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateabbrev', models.CharField(max_length=2)),
                ('state', models.CharField(max_length=14)),
                ('population', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'OpiodPages_state',
            },
        ),
        migrations.CreateModel(
            name='Triple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpiodPages.drug')),
                ('pd_prescriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpiodPages.pd_prescriber')),
            ],
            options={
                'db_table': 'OpiodPages_triple',
            },
        ),
        migrations.CreateModel(
            name='Prescriber_Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpiodPages.credential')),
                ('npi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpiodPages.pd_prescriber')),
            ],
        ),
        migrations.AddField(
            model_name='pd_prescriber',
            name='drug',
            field=models.ManyToManyField(through='OpiodPages.Triple', to='OpiodPages.Drug'),
        ),
        migrations.AddField(
            model_name='pd_prescriber',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OpiodPages.state'),
        ),
    ]
