# Generated by Django 3.2.8 on 2021-12-04 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpiodPages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pd_prescriber',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='OpiodPages.state'),
        ),
        migrations.AlterField(
            model_name='prescriber_credential',
            name='credid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='OpiodPages.credential'),
        ),
        migrations.AlterField(
            model_name='prescriber_credential',
            name='npi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='OpiodPages.pd_prescriber'),
        ),
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='triple',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='OpiodPages.drug'),
        ),
        migrations.AlterField(
            model_name='triple',
            name='pd_prescriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='OpiodPages.pd_prescriber'),
        ),
        migrations.AlterModelTable(
            name='prescriber_credential',
            table='OpiodPages_prescriber_credential',
        ),
    ]
