# Generated by Django 3.2.8 on 2021-12-06 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpiodPages', '0002_auto_20211204_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pd_prescriber',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OpiodPages.state'),
        ),
        migrations.AlterField(
            model_name='prescriber_credential',
            name='credid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpiodPages.credential'),
        ),
        migrations.AlterField(
            model_name='prescriber_credential',
            name='npi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpiodPages.pd_prescriber'),
        ),
        migrations.AlterField(
            model_name='triple',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpiodPages.drug'),
        ),
        migrations.AlterField(
            model_name='triple',
            name='pd_prescriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpiodPages.pd_prescriber'),
        ),
    ]
